// <auto-generated />
using System;
using KindleKeep.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace kindlekeep_api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(KindleDbContext))]
    [Migration("20260726013418_AddCopilotCacheToSecurityAudits")]
    partial class AddCopilotCacheToSecurityAudits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.AlertIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EscalatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IncidentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MonitorId");

                    b.ToTable("AlertIncidents");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.JourneyStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssertEquals")
                        .HasColumnType("text");

                    b.Property<string>("AssertJsonPath")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<string>("CaptureAs")
                        .HasColumnType("text");

                    b.Property<string>("CaptureJsonPath")
                        .HasColumnType("text");

                    b.Property<int?>("ExpectedStatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.Property<string>("UrlOrPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MonitorId", "StepOrder")
                        .IsUnique();

                    b.ToTable("JourneySteps");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.MonitorTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<char>("CurrentSecurityGrade")
                        .HasColumnType("character(1)");

                    b.Property<int>("CurrentUptimeStatus")
                        .HasColumnType("integer");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("LastAuditHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MonitorType")
                        .HasColumnType("integer");

                    b.Property<string>("PublicSlug")
                        .HasColumnType("text");

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("text");

                    b.Property<int>("RequestTimeout")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PublicSlug")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("MonitorTargets");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.SecurityAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CopilotExplanation")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CopilotGeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasCsp")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasHsts")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasNosniff")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasXfo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawHeaders")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SslExpiryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SslIssuer")
                        .HasColumnType("text");

                    b.Property<string>("TlsVersion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MonitorId");

                    b.ToTable("SecurityAudits");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.StatusPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("StatusPages");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.StatusPageService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid");

                    b.Property<string>("SectionName")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("StatusPageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MonitorId");

                    b.HasIndex("StatusPageId", "MonitorId")
                        .IsUnique();

                    b.ToTable("StatusPageServices");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.UptimeLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<bool>("IsColdStart")
                        .HasColumnType("boolean");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MonitorId");

                    b.ToTable("UptimeLogs");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuthProvider")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DigestEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("DiscordWebhookUrl")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EnableEmailNotifications")
                        .HasColumnType("boolean");

                    b.Property<int>("EscalationDelayMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GithubWebhookSecret")
                        .HasColumnType("text");

                    b.Property<string>("SlackWebhookUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.AlertIncident", b =>
                {
                    b.HasOne("KindleKeep.Api.Core.Entities.MonitorTarget", "Monitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monitor");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.ApiKey", b =>
                {
                    b.HasOne("KindleKeep.Api.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.JourneyStep", b =>
                {
                    b.HasOne("KindleKeep.Api.Core.Entities.MonitorTarget", "Monitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monitor");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.MonitorTarget", b =>
                {
                    b.HasOne("KindleKeep.Api.Core.Entities.User", "User")
                        .WithMany("Monitors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.SecurityAudit", b =>
                {
                    b.HasOne("KindleKeep.Api.Core.Entities.MonitorTarget", "Monitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monitor");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.StatusPage", b =>
                {
                    b.HasOne("KindleKeep.Api.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.StatusPageService", b =>
                {
                    b.HasOne("KindleKeep.Api.Core.Entities.MonitorTarget", "Monitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KindleKeep.Api.Core.Entities.StatusPage", "StatusPage")
                        .WithMany("Services")
                        .HasForeignKey("StatusPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monitor");

                    b.Navigation("StatusPage");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.UptimeLog", b =>
                {
                    b.HasOne("KindleKeep.Api.Core.Entities.MonitorTarget", "Monitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monitor");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.StatusPage", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.User", b =>
                {
                    b.Navigation("Monitors");
                });
#pragma warning restore 612, 618
        }
    }
}
